In [1]:
import moire_lattice_vector_finder_BACKUP as mlf
import numpy as np
import pandas as pd
import time

In [2]:
file_1 = "graphene_monolayer.vasp"
file_2 = "graphene_monolayer.vasp"

In [3]:
lattice_vectors1, atom_type_arr1, dat1 = mlf.read_vasp(file_1)

In [4]:
lattice_vectors2, atom_type_arr2, dat2 = mlf.read_vasp(file_2)

In [5]:
mlf.angle_between(lattice_vectors1['a'],lattice_vectors1['b'])

120.00000000044221

In [6]:
import multiprocessing 
multiprocessing.cpu_count()

64

In [7]:
start = time.time()
test = mlf.find_index(a1=lattice_vectors1['a'],a2=lattice_vectors1['b'],a3=lattice_vectors1['c'],
                    b1=lattice_vectors2['a'],b2=lattice_vectors2['b'],b3=lattice_vectors2['c'],
                    theta_min=0.08,theta_max=45.01,theta_step=0.05,
                    n_min = 1, n_max=100,
                    dtol = 0.09, ang_lat = 60.0, num_cores=64)
end = time.time()
print(f"Time taken: {end-start} secs")

Time taken: 1765.1429483890533 secs

In [8]:
# Define the column names
columns = ['degree', 'n1', 'n2', 'n1p', 'n2p','vec_del', 'delta_angle', 'norm','A1','A2']
df = pd.DataFrame(test, columns=columns)
len(df)

192652

In [9]:
# Sort the DataFrame by 'degree' in ascending order and 'norm' in descending order, followed by 'vec_del' and 'delta_angle'
df_sorted = df.sort_values(by=['degree', 'norm', 'vec_del', 'delta_angle','n1','n2'], ascending=[True, True, True, True, False, False])

In [10]:
df_sorted.head()

,degree,n1,n2,n1p,n2p,vec_del,delta_angle,norm,A1,A2
438,0.9,1,2,2,1,0.067127,4.422205e-10,7.401874,"[3.7009368923999997, 2.1367369111, 0.0]","[3.7009368923999997, -2.1367369111, 0.0]"
409,0.9,-1,-2,-2,-1,0.067127,4.422205e-10,7.401874,"[-3.7009368923999997, -2.1367369111, -0.0]","[-3.7009368923999997, 2.1367369111, -0.0]"
443,0.9,2,1,1,2,0.067127,4.422205e-10,7.401874,"[3.7009368923999997, -2.1367369111, 0.0]","[3.7009368923999997, 2.1367369111, 0.0]"
404,0.9,-2,-1,-1,-2,0.067127,4.422205e-10,7.401874,"[-3.7009368923999997, 2.1367369111, -0.0]","[-3.7009368923999997, -2.1367369111, -0.0]"
437,0.9,1,2,-1,1,0.067127,2.211067e-10,7.401874,"[3.7009368923999997, 2.1367369111, 0.0]","[0.0, 4.2734738222, 0.0]"

In [11]:
# Group by 'degree' and take the first entry in each group
final_df = df_sorted.groupby('degree', as_index=False).first()

In [12]:
len(final_df)

300

In [13]:
final_df

,degree,n1,n2,n1p,n2p,vec_del,delta_angle,norm,A1,A2
0,0.90,1,2,2,1,0.067127,4.422205e-10,7.401874,"[3.7009368923999997, 2.1367369111, 0.0]","[3.7009368923999997, -2.1367369111, 0.0]"
1,0.92,1,2,2,1,0.068619,4.422205e-10,7.401874,"[3.7009368923999997, 2.1367369111, 0.0]","[3.7009368923999997, -2.1367369111, 0.0]"
2,0.94,2,1,1,2,0.070110,4.422205e-10,7.401874,"[3.7009368923999997, -2.1367369111, 0.0]","[3.7009368923999997, 2.1367369111, 0.0]"
3,0.96,2,1,1,2,0.071602,4.422205e-10,7.401874,"[3.7009368923999997, -2.1367369111, 0.0]","[3.7009368923999997, 2.1367369111, 0.0]"
4,0.98,2,1,1,2,0.073094,4.422205e-10,7.401874,"[3.7009368923999997, -2.1367369111, 0.0]","[3.7009368923999997, 2.1367369111, 0.0]"
...,...,...,...,...,...,...,...,...,...,...
295,30.00,41,11,30,41,0.067126,3.831531e-10,157.075598,"[64.14957280159999, -64.10210733299999, 0.0]","[87.5888397868, 23.504106022100004, 0.0]"
296,30.02,4,15,15,11,0.080109,3.823644e-10,57.493710,"[23.4392669852, 23.504106022099997, 0.0]","[32.0747864008, -8.5469476444, 0.0]"
297,30.04,4,15,15,11,0.068522,3.823644e-10,57.493710,"[23.4392669852, 23.504106022099997, 0.0]","[32.0747864008, -8.5469476444, 0.0]"
298,30.06,15,11,4,15,0.056936,3.823644e-10,57.493710,"[32.0747864008, -8.5469476444, 0.0]","[23.4392669852, 23.504106022099997, 0.0]"
299,30.08,15,11,4,15,0.045349,3.823644e-10,57.493710,"[32.0747864008, -8.5469476444, 0.0]","[23.4392669852, 23.504106022099997, 0.0]"

In [14]:
final_df.to_csv('graphene_bilayer_candidates.csv')

In [15]:
final_df.to_pickle('graphene_bilayer_candidates.pkl')

# Third layer Doamin

In [ ]:
lattice_vectors3, atom_type_arr3, dat3 = acf.read_vasp(file_3)

In [ ]:
lattice_vectors3

In [ ]:
for i,row in final_df.iterrows():
    if i == 12:
        
        print(i)
        print(f"Degree: {row['degree']}")
        moire_vector_a = np.array(row['A1'])
        moire_vector_b = np.array(row['A2'])
        moire_vector_c = np.array([0.0,0.0,1.0])
        print(f"Moire Vector A: {moire_vector_a}")
        print(f"Moire Vector B: {moire_vector_b}")
        print(f"Moire Vector C: {moire_vector_c}")
        print(f"Lattice Vector A: {lattice_vectors3['a']}")
        print(f"Lattice Vector B: {lattice_vectors3['b']}")
        print(f"Lattice Vector C: {lattice_vectors3['c']}")
        test2 = acf.find_index(a1=moire_vector_a,a2=moire_vector_b,a3=moire_vector_c,
                        b1=lattice_vectors3['a'],b2=lattice_vectors3['b'],b3=lattice_vectors3['c'],
                        theta_min=12,theta_max=14.0,theta_step=0.01,
                        n_min = 1, n_max=40,d_tol = 0.01, ang_lat = 60.0)
        
        break

In [ ]:
test2

In [ ]:
# Define the column names
columns = ['degree', 'n1', 'n2', 'n1p', 'n2p','vec_del', 'delta_angle', 'norm','A1','A2']
df = pd.DataFrame(test2, columns=columns)
len(df)

In [ ]:
df_sorted = df.sort_values(by=['degree', 'norm','vec_del', 'delta_angle'])

In [ ]:
# Group by 'degree' and take the first entry in each group
final2_df = df_sorted.groupby('degree', as_index=False).first()
len(final2_df)

In [ ]:
final2_df['theta']= 21.79

In [ ]:
final2_df.sort_values(by=['vec_del'])

In [ ]:
np.__version__

In [1]:
for sign1 in [-1, 1]:
    for sign2 in [-1, 1]:
        print(sign1,sign2)

-1 -1
-1 1
1 -1
1 1

In [6]:
theta_array = np.array([i + offset for i in range(1, 31) for offset in np.arange(-0.1, 0.1, 0.02)])
print(theta_array)
print(len(theta_array))

[ 0.9   0.92  0.94  0.96  0.98  1.    1.02  1.04  1.06  1.08  1.9   1.92
  1.94  1.96  1.98  2.    2.02  2.04  2.06  2.08  2.9   2.92  2.94  2.96
  2.98  3.    3.02  3.04  3.06  3.08  3.9   3.92  3.94  3.96  3.98  4.
  4.02  4.04  4.06  4.08  4.9   4.92  4.94  4.96  4.98  5.    5.02  5.04
  5.06  5.08  5.9   5.92  5.94  5.96  5.98  6.    6.02  6.04  6.06  6.08
  6.9   6.92  6.94  6.96  6.98  7.    7.02  7.04  7.06  7.08  7.9   7.92
  7.94  7.96  7.98  8.    8.02  8.04  8.06  8.08  8.9   8.92  8.94  8.96
  8.98  9.    9.02  9.04  9.06  9.08  9.9   9.92  9.94  9.96  9.98 10.
 10.02 10.04 10.06 10.08 10.9  10.92 10.94 10.96 10.98 11.   11.02 11.04
 11.06 11.08 11.9  11.92 11.94 11.96 11.98 12.   12.02 12.04 12.06 12.08
 12.9  12.92 12.94 12.96 12.98 13.   13.02 13.04 13.06 13.08 13.9  13.92
 13.94 13.96 13.98 14.   14.02 14.04 14.06 14.08 14.9  14.92 14.94 14.96
 14.98 15.   15.02 15.04 15.06 15.08 15.9  15.92 15.94 15.96 15.98 16.
 16.02 16.04 16.06 16.08 16.9  16.92 16.94 16.96 16.98 17.   17.02 17.04
 17.06 17.08 17.9  17.92 17.94 17.96 17.98 18.   18.02 18.04 18.06 18.08
 18.9  18.92 18.94 18.96 18.98 19.   19.02 19.04 19.06 19.08 19.9  19.92
 19.94 19.96 19.98 20.   20.02 20.04 20.06 20.08 20.9  20.92 20.94 20.96
 20.98 21.   21.02 21.04 21.06 21.08 21.9  21.92 21.94 21.96 21.98 22.
 22.02 22.04 22.06 22.08 22.9  22.92 22.94 22.96 22.98 23.   23.02 23.04
 23.06 23.08 23.9  23.92 23.94 23.96 23.98 24.   24.02 24.04 24.06 24.08
 24.9  24.92 24.94 24.96 24.98 25.   25.02 25.04 25.06 25.08 25.9  25.92
 25.94 25.96 25.98 26.   26.02 26.04 26.06 26.08 26.9  26.92 26.94 26.96
 26.98 27.   27.02 27.04 27.06 27.08 27.9  27.92 27.94 27.96 27.98 28.
 28.02 28.04 28.06 28.08 28.9  28.92 28.94 28.96 28.98 29.   29.02 29.04
 29.06 29.08 29.9  29.92 29.94 29.96 29.98 30.   30.02 30.04 30.06 30.08]
300

In [2]:
np.sqrt(1.2336456308**2 + 2.1367369111**2)

2.4672912616164915

In [17]:
for sign1 in np.arange(-1,2,2):
    for sign2 in np.arange(-1,2,2):
        print(sign1,sign2)

-1 -1
-1 1
1 -1
1 1